substitutions:
  _REGION: us-central1
  _REPO: cricket-repo
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/app:${SHORT_SHA}'

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', '.']

# Step 2: Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']

# Step 3: Authenticate to GKE and deploy
- - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
    - -c
    - |
      gcloud container clusters get-credentials cricket-cluster --zone=us-central1-a --project=x-landing-466108-p9
      sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/x-landing-466108-p9/cricket-repo/app:c22c5ed|" k8s/deployment.yaml
      kubectl apply -f k8s/


images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY


