steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/app:v1", "."]
  
  # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/app:v1"]

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run=filename=app.yaml
      - --location=us-central1
      - --cluster=cricket-cluster
options:
  logging: CLOUD_LOGGING_ONLY

