substitutions:
  _REGION: us-central1
  _REPO: cricket-repo
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/app:${SHORT_SHA}'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials cricket-cluster --zone=us-central1-a --project=${PROJECT_ID}
        sed "s|IMAGE_PLACEHOLDER|${_IMAGE}|" k8s/deployment.yaml > k8s/deployment-patched.yaml
        kubectl apply -f k8s/deployment-patched.yaml
        kubectl apply -f k8s/service.yaml

images:
  - '${_IMAGE}'


options:
  logging: CLOUD_LOGGING_ONLY


