steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/x-landing-466108-p9/live-cricket-score-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/x-landing-466108-p9/live-cricket-score-app']

images:
  - 'gcr.io/x-landing-466108-p9/live-cricket-score-app'

options:
  logging: CLOUD_LOGGING_ONLY

