substitutions:
  _REGION: us-central1
  _REPO: cricket-repo
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/app:${SHORT_SHA}'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  -  name: "gcr.io/cloud-builders/gke-deploy"
     args:
     - run
     - --filename=app.yaml
     - --location=us-central1
     - --cluster=autopilot-cluster-1
images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY

