apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricket-app
  template:
    metadata:
      labels:
        app: cricket-app
    spec:
      containers:
      - name: app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000